### ISSUE TITLE
Implement a permissions system for commands

### ISSUE THREAD

**Issue by rrredface** [balancetf/balancetf-bot#1]
Currently all users have the ability to use any command. Not a good thing.
Permissions will reside in conf.toml
I envision something like this:

```toml
[permissions]
maintainer_id = ["btf.startvote", "btf.vote"]
keynote_id = ["btf.vote_keynote"]
member_id = ["btf.vote"]
```

The `Command` struct in `src/model/command.rs` will have an additional field: `permission: String`
